#!/usr/bin/perl -w

use strict;

# get command-line arguments

if ( scalar @ARGV != 7 ) {
  die qq{Usage: $0 original_y4m previous_iteration_ivf previous_iteration_entering_state entering_state output_ivf exiting_state reencode_first};
}

my ( $original_y4m, $previous_iteration_ivf,
     $previous_iteration_entering_state, $entering_state,
     $output_ivf, $exiting_state, $reencode_first ) = @ARGV;

# run xc-enc

my $extra_arg = "";

if ( $reencode_first eq "yes" ) {
  $extra_arg = "--reencode-first-frame";
}

system qq{xc-enc ${extra_arg} -i y4m -r -I ${entering_state} -O ${exiting_state} -S ${previous_iteration_entering_state} -p ${previous_iteration_ivf} -o ${output_ivf} --refine-sw ${original_y4m}}
  and die q{xc-enc exiting with error};
